AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Agent 
  SAM Template for AWS Strands Agent

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13

Parameters:
  TwilioAccountIDSIDSecretName:
    Type: String
    Default: "TWILIO_ACCOUNT_SID"
    Description: "Name of the secret in AWS Secrets Manager for Twilio Account SID"
  TwilioAccessTokenSecretName:
    Type: String
    Default: "TWILIO_AUTH_TOKEN"
    Description: "Name of the secret in AWS Secrets Manager for Twilio Account Auth Token"
  GoogleAPIKeySecretName:
    Type: String
    Default: "GOOGLE_API_KEY"
    Description: "Name of the secret in AWS Secrets Manager for GEMINI Model API Key"
  WhatsappNumberSecretName:
    Type: String
    Default: "MY_WHATSAPP_ID"
    Description: "Name of the secret in AWS Secrets Manager for Whatsapp Number"

Resources:
  MyAgenticRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: my-strandsagent-api
      Parameters:
        endpointConfigurationTypes: REGIONAL
      Description: "Strands Agent API Endpoint"
      BinaryMediaTypes:
        - 'application/json'
  
  MyAgenticRestApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt MyAgenticRestApi.RootResourceId
      PathPart: genai
      RestApiId: !Ref MyAgenticRestApi

  MyAgenticRestApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref MyAgenticRestApiResource
      RestApiId: !Ref MyAgenticRestApi
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StrandsLambda.Arn}/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: MyAgenticRestApiMethod 
    Properties:
      RestApiId: !Ref MyAgenticRestApi
      Description: 'Deployment for api v1.0'
 
  ApiProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref MyAgenticRestApi
      StageName: prod

  StrandsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-strandsagent-lambda
      CodeUri: src/
      Handler: app.lambda_handler
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy: 
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${TwilioAccountIDSIDSecretName}-*"
        - AWSSecretsManagerGetSecretValuePolicy: 
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${TwilioAccessTokenSecretName}-*"
        - AWSSecretsManagerGetSecretValuePolicy: 
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${GoogleAPIKeySecretName}-*"
        - AWSSecretsManagerGetSecretValuePolicy: 
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${WhatsappNumberSecretName}-*"
        - Statement:
            - Effect: Allow
              Action:
                - ec2:*
              Resource: "*"
            - Effect: Allow
              Action:
                - bedrock:*
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:*
              Resource: "*"

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StrandsLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyAgenticRestApi}/*/POST/genai

Outputs:
  StackCreationSuccess:
    Description: "Strands Agent Stack"
    Value: "Strands Agent Created Successfully"
  StrandsLambdaArn:
    Description: "Strands Lambda ARN"
    Value: !GetAtt StrandsLambda.Arn